import type {
  Account,
  AppNotification,
  Bill,
  CalendarEvent,
  Contact,
  Document,
  HomeItem,
  HomeService,
  Household,
  HouseholdMember,
  ImportantDate,
  Place,
  Profile,
  Subscription,
  Task,
} from "@veedu/types";

const now = new Date().toISOString();
const today = new Date();
function isoDays(offset: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
}
function isoAt(offset: number, hour: number, minute = 0): string {
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const DEMO_USER_ID = "00000000-0000-4000-8000-000000000001";
export const DEMO_PARTNER_ID = "00000000-0000-4000-8000-000000000002";
export const DEMO_HOUSEHOLD_ID = "00000000-0000-4000-8000-000000000010";

export interface DemoStore {
  profile: Profile;
  household: Household;
  members: HouseholdMember[];
  tasks: Task[];
  events: CalendarEvent[];
  bills: Bill[];
  subscriptions: Subscription[];
  documents: Document[];
  accounts: Account[];
  contacts: Contact[];
  places: Place[];
  importantDates: ImportantDate[];
  homeItems: HomeItem[];
  homeServices: HomeService[];
  notifications: AppNotification[];
}

export function createDemoStore(): DemoStore {
  return {
    profile: {
      id: DEMO_USER_ID,
      email: "demo@veedu.app",
      full_name: "Senthil Kumar",
      avatar_url: null,
      timezone: "Europe/Brussels",
      currency: "EUR",
      created_at: now,
      updated_at: now,
    },
    household: {
      id: DEMO_HOUSEHOLD_ID,
      name: "Veedu Home",
      home_location: "Antwerp",
      parents_location: "Dindigul",
      timezone: "Europe/Brussels",
      currency: "EUR",
      created_by: DEMO_USER_ID,
      created_at: now,
      updated_at: now,
    },
    members: [
      {
        id: "m1",
        household_id: DEMO_HOUSEHOLD_ID,
        user_id: DEMO_USER_ID,
        role: "owner",
        status: "active",
        display_name: "Senthil",
        created_at: now,
      },
      {
        id: "m2",
        household_id: DEMO_HOUSEHOLD_ID,
        user_id: DEMO_PARTNER_ID,
        role: "member",
        status: "active",
        display_name: "Partner",
        created_at: now,
      },
    ],
    tasks: [
      {
        id: "t1",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Renew electricity contract",
        description: "Compare tariffs and renew before expiry",
        category_id: null,
        category: "Finance",
        priority: "high",
        status: "todo",
        owner_id: DEMO_USER_ID,
        due_date: isoDays(1),
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "t2",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Prepare documents",
        description: null,
        category_id: null,
        category: "Family",
        priority: "medium",
        status: "in_progress",
        owner_id: DEMO_USER_ID,
        due_date: isoDays(3),
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "t3",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Buy groceries",
        description: null,
        category_id: null,
        category: "Home",
        priority: "low",
        status: "todo",
        owner_id: DEMO_PARTNER_ID,
        due_date: isoDays(0),
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "t4",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Complete personal certification",
        description: "Private study plan",
        category_id: null,
        category: "Personal",
        priority: "medium",
        status: "todo",
        owner_id: DEMO_USER_ID,
        due_date: isoDays(10),
        visibility: "private",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "t5",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Book boiler service",
        description: null,
        category_id: null,
        category: "Home",
        priority: "urgent",
        status: "done",
        owner_id: DEMO_USER_ID,
        due_date: isoDays(-2),
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    events: [
      {
        id: "e1",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Team Sync",
        start_at: isoAt(0, 9, 30),
        end_at: isoAt(0, 10, 0),
        location: "Online",
        notes: null,
        participants: ["Senthil"],
        visibility: "private",
        owner_id: DEMO_USER_ID,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
      },
      {
        id: "e2",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Dentist",
        start_at: isoAt(0, 11, 0),
        end_at: isoAt(0, 11, 45),
        location: "Antwerp",
        notes: null,
        participants: ["Senthil"],
        visibility: "shared",
        owner_id: DEMO_USER_ID,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
      },
      {
        id: "e3",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Dinner",
        start_at: isoAt(0, 18, 30),
        end_at: isoAt(0, 20, 0),
        location: "Home",
        notes: null,
        participants: ["Senthil", "Partner"],
        visibility: "shared",
        owner_id: DEMO_USER_ID,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
      },
      {
        id: "e4",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Read & Plan",
        start_at: isoAt(0, 20, 0),
        end_at: isoAt(0, 21, 0),
        location: null,
        notes: null,
        participants: [],
        visibility: "private",
        owner_id: DEMO_USER_ID,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
      },
    ],
    bills: [
      {
        id: "b1",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Electricity",
        provider: "Engie",
        amount: 82.4,
        currency: "EUR",
        due_date: isoDays(1),
        frequency: "monthly",
        category: "Utilities",
        status: "due",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "b2",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Internet",
        provider: "Proximus",
        amount: 49,
        currency: "EUR",
        due_date: isoDays(9),
        frequency: "monthly",
        category: "Utilities",
        status: "upcoming",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "b3",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Rent",
        provider: "Landlord",
        amount: 1116.6,
        currency: "EUR",
        due_date: isoDays(5),
        frequency: "monthly",
        category: "Housing",
        status: "upcoming",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    subscriptions: [
      {
        id: "s1",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Netflix",
        provider: "Netflix",
        amount: 17.99,
        currency: "EUR",
        billing_frequency: "monthly",
        next_renewal: isoDays(4),
        category: "Entertainment",
        status: "active",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        payment_reference: null,
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "s2",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Domain",
        provider: "Namecheap",
        amount: 14.5,
        currency: "EUR",
        billing_frequency: "yearly",
        next_renewal: isoDays(18),
        category: "Tech",
        status: "active",
        owner_id: DEMO_USER_ID,
        visibility: "private",
        payment_reference: null,
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "s3",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Insurance",
        provider: "AG Insurance",
        amount: 42,
        currency: "EUR",
        billing_frequency: "monthly",
        next_renewal: isoDays(42),
        category: "Insurance",
        status: "active",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        payment_reference: null,
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    documents: [
      {
        id: "d1",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Residence Permit",
        category_id: null,
        category: "Identity",
        status: "expiring_soon",
        issued_at: "2024-01-15",
        expires_at: isoDays(47),
        file_path: "households/demo/documents/d1/residence-permit.pdf",
        file_name: "residence-permit.pdf",
        mime_type: "application/pdf",
        owner_id: DEMO_USER_ID,
        visibility: "private",
        notes: "Renewal appointment pending",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "d2",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Driving License",
        category_id: null,
        category: "Identity",
        status: "valid",
        issued_at: "2018-06-01",
        expires_at: "2030-06-01",
        file_path: "households/demo/documents/d2/license.pdf",
        file_name: "license.pdf",
        mime_type: "application/pdf",
        owner_id: DEMO_USER_ID,
        visibility: "private",
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "d3",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Passport",
        category_id: null,
        category: "Identity",
        status: "valid",
        issued_at: "2021-03-10",
        expires_at: "2031-03-10",
        file_path: "households/demo/documents/d3/passport.pdf",
        file_name: "passport.pdf",
        mime_type: "application/pdf",
        owner_id: DEMO_USER_ID,
        visibility: "private",
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "d4",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Rental Agreement",
        category_id: null,
        category: "Housing",
        status: "valid",
        issued_at: "2023-09-01",
        expires_at: null,
        file_path: "households/demo/documents/d4/rental.pdf",
        file_name: "rental.pdf",
        mime_type: "application/pdf",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    accounts: [
      {
        id: "a1",
        household_id: DEMO_HOUSEHOLD_ID,
        institution: "ING",
        nickname: "Household Current",
        account_type: "Current",
        reference: null,
        last_four: "4832",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        notes: "Primary household account — no secrets stored",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "a2",
        household_id: DEMO_HOUSEHOLD_ID,
        institution: "BNP Paribas Fortis",
        nickname: "Savings",
        account_type: "Savings",
        reference: null,
        last_four: "9012",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        notes: null,
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    contacts: [
      {
        id: "c1",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Dr. John Smith",
        phone: "+32 xxx xxx xxx",
        email: "john@example.com",
        address: "Antwerp",
        category: "Doctors",
        notes: "Dentist",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "c2",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Building Manager",
        phone: "+32 3 000 0000",
        email: null,
        address: null,
        category: "Service Providers",
        notes: null,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    places: [
      {
        id: "p1",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Ghent",
        address: "Belgium",
        website: null,
        rating: 5,
        category: "Weekend",
        tags: ["weekend", "city"],
        notes: "Saved by both",
        visited: true,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    importantDates: [
      {
        id: "id1",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Father's Birthday",
        date: isoDays(9),
        category: "Birthdays",
        notes: null,
        reminder_days: 3,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "id2",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Insurance Renewal",
        date: isoDays(27),
        category: "Renewals",
        notes: null,
        reminder_days: 14,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "id3",
        household_id: DEMO_HOUSEHOLD_ID,
        title: "Travel",
        date: isoDays(75),
        category: "Travel",
        notes: "Family trip planning",
        reminder_days: 30,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    homeItems: [
      {
        id: "hi1",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Washing Machine",
        category: "Appliances",
        purchased_at: "2024-06-01",
        warranty_until: "2027-06-01",
        notes: null,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    homeServices: [
      {
        id: "hs1",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Boiler service",
        provider: "Local HVAC",
        last_serviced_at: "2025-10-01",
        next_due_at: isoDays(24),
        notes: null,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "hs2",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Air conditioner",
        provider: null,
        last_serviced_at: "2026-05-01",
        next_due_at: null,
        notes: null,
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
      {
        id: "hs3",
        household_id: DEMO_HOUSEHOLD_ID,
        name: "Water filter",
        provider: null,
        last_serviced_at: null,
        next_due_at: isoDays(12),
        notes: "Replace cartridge",
        owner_id: DEMO_USER_ID,
        visibility: "shared",
        created_by: DEMO_USER_ID,
        created_at: now,
        updated_at: now,
        archived_at: null,
      },
    ],
    notifications: [
      {
        id: "n1",
        household_id: DEMO_HOUSEHOLD_ID,
        user_id: DEMO_USER_ID,
        title: "Residence permit expires in 47 days",
        body: "Start renewal paperwork soon.",
        priority: "high",
        href: "/documents/d1",
        read_at: null,
        created_at: now,
      },
      {
        id: "n2",
        household_id: DEMO_HOUSEHOLD_ID,
        user_id: DEMO_USER_ID,
        title: "Electricity bill is due tomorrow",
        body: "€82.40 expected.",
        priority: "high",
        href: "/bills",
        read_at: null,
        created_at: now,
      },
      {
        id: "n3",
        household_id: DEMO_HOUSEHOLD_ID,
        user_id: DEMO_USER_ID,
        title: "Netflix renews in 4 days",
        body: "€17.99 / month",
        priority: "normal",
        href: "/subscriptions",
        read_at: now,
        created_at: now,
      },
    ],
  };
}

let singleton: DemoStore | null = null;

export function getDemoStore(): DemoStore {
  if (!singleton) singleton = createDemoStore();
  return singleton;
}

export function resetDemoStore(): DemoStore {
  singleton = createDemoStore();
  return singleton;
}

export function uid(prefix = "id"): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
}
